apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: $MYPROJECT
      app.kubernetes.io/component: $MYPROJECT
      app.kubernetes.io/instance: $MYPROJECT
    name: $MYPROJECT
  spec:
    dockerImageRepository: $MYREGISTRY/$MYNAMESPACE/$MYPROJECT
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: $MYPROJECT
      app.kubernetes.io/component: $MYPROJECT
      app.kubernetes.io/instance: $MYPROJECT
    name: $MYPROJECT
  spec:
    nodeSelector: null
    output:
      to:
        kind: DockerImage
        name: $MYREGISTRY/$MYNAMESPACE/$MYPROJECT:latest
      pushSecret:
        name: push-secret
    postCommit: {}
    resources: {}
    source:
      git:
        uri: $REPO_URL
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ubi:latest
      type: Docker
    triggers:
    - github:
        secret: $SECRET_GITHUB
      type: GitHub
    - generic:
        secret: $SECRET_GENERIC
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: $MYPROJECT
      app.kubernetes.io/component: $MYPROJECT
      app.kubernetes.io/instance: $MYPROJECT
    name: $MYPROJECT
  spec:
    replicas: 1
    selector:
      deploymentconfig: $MYPROJECT
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deploymentconfig: $MYPROJECT
      spec:
        containers:
        - image: $MYREGISTRY/$MYNAMESPACE/$MYPROJECT:latest
          name: $MYPROJECT
          ports:
          - containerPort: 3000
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - $MYPROJECT
        from:
          kind: ImageStreamTag
          name: $MYPROJECT:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: $MYPROJECT
      app.kubernetes.io/component: $MYPROJECT
      app.kubernetes.io/instance: $MYPROJECT
    name: $MYPROJECT
  spec:
    ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      deploymentconfig: $MYPROJECT
  status:
    loadBalancer: {}
kind: List
metadata: {}
